controllers/ArticleController.php
<?php

namespace app\controllers;


use app\models\Article;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\ActiveQuery;

class ArticleController extends TextController
{
    public function findModel() {
        $params = $this->primaryKey();
        $model = Article::findOne($params);
        if (!$model) {
            $model = new Article($params);
            $model->loadFile();
        }
        return $model;
    }
}

controllers/HomeController.php
<?php

namespace app\controllers;


use Yii;
use yii\web\Controller;
use yii\web\Response;

class HomeController extends Controller {

    public function actionIndex() {
        return $this->render('index');
    }

    public function actionInfo() {
        Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'id' => Yii::$app->id,
            'language' => Yii::$app->language,
            'modules' => array_keys(Yii::$app->modules),
            'bootstrap' => Yii::$app->bootstrap,
            'version' => Yii::$app->version,
        ];
    }

    public function actionError() {
        return Yii::$app->getErrorHandler()->exception->getMessage();
    }
}

controllers/UserController.php
<?php

namespace app\controllers;


use app\models\LoginForm;
use app\models\PasswordForm;
use app\models\RequestForm;
use app\models\User;
use app\models\WalletForm;
use Yii;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

class UserController extends Controller {
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'login', 'logout', 'request', 'reset', 'password', 'reset-auth'],
                'rules' => [
                    [
                        'actions' => ['create', 'login', 'request', 'reset'],
                        'allow' => true,
                        'roles' => ['?']
                    ],
                    [
                        'actions' => ['logout', 'update', 'password', 'reset-auth'],
                        'allow' => true,
                        'roles' => ['@']
                    ],
                ]
            ]
        ];
    }

    public function actionIndex($referral_id = null) {
        return $this->render('index', [
            'dataProvider' => new ActiveDataProvider([
                'query' => User::find()->andFilterWhere(['referral_id' => $referral_id]),
                'sort' => [
                    'defaultOrder' => ['id' => SORT_DESC]
                ]
            ])
        ]);
    }

    public function actionLogin() {
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user && $user->validatePassword($model->password)) {
                if (empty($user->auth)) {
                    $user->generateAuthKey();
                    $user->save(true, ['auth']);
                }

                if (Yii::$app->user->login($user)) {
                    return $this->redirect(['view', 'id' => $user->id]);
                }
            }
            else {
                Yii::$app->session->setFlash('error', Yii::t('app', 'Invalid username or password'));
            }
        }

        return $this->render('login', [
            'model' => $model
        ]);
    }

    public function actionLogout($destroy = false) {
        Yii::$app->user->logout($destroy);
        return $this->goHome();
    }

    public function actionResetAuth($id) {
        if (!Yii::$app->user->can('manage') && $id != Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }
        $model = $this->findModel($id);
        $model->generateAuthKey();
        if ($model->save(false)) {
            Yii::$app->session->addFlash('success', Yii::t('app', 'Logout done'));
        }
        return $this->goHome();
    }

    public function actionCreate($referral_id = null) {
        $model = new User(['referral_id' => $referral_id]);
        Yii::$app->view->title = Yii::t('app', 'Signup');
        return $this->edit($model);
    }

    public function actionUpdate($id = null) {
        $model = $this->findModel($id);
        Yii::$app->view->title = Yii::t('app', 'Update');
        return $this->edit($model);
    }

    public function actionView($id = null) {
        if (empty($id)) {
            return $this->redirect(['user/view', 'id' => Yii::$app->user->id]);
        }
        $model = $this->findModel($id);
        return $this->render('view', [
            'model' => $model
        ]);
    }

    public function findModel($id = null) {
        /** @var User $model */
        if ($id) {
            $model = User::findOne($id);
            if (!$model) {
                throw new NotFoundHttpException();
            }
        }
        else {
            $model = Yii::$app->user->identity;
        }
        return $model;
    }

    public function actionPassword($id) {
        if (!Yii::$app->user->can('manage') && $id != Yii::$app->user->id) {
            throw new ForbiddenHttpException();
        }
        $user = $this->findModel($id);
        $model = new PasswordForm();
        if ($this->password($user, $model)) {
            return $this->redirect(['view', 'id' => $id]);
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionReset($code) {
        /** @var User $user */
        $user = User::findOne(['code' => $code]);
        if (!$user) {
            Yii::$app->session->addFlash('error', Yii::t('app', 'Invalid code'));
            return $this->goHome();
        }
        $model = new PasswordForm();
        $user->code = null;
        if ($this->password($user, $model)) {
            return $this->redirect(['login']);
        }
        return $this->render('password', [
            'model' => $model
        ]);
    }

    public function actionRequest() {
        $model = new RequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user = $model->getUser();
            if ($user) {
                $user->generateCode();
                if ($user->save(false)) {
                    $url = Url::to(['reset', 'code' => $user->code], true);
                    $content = Yii::t('app', 'To recover your password, open <a href="{url}">this link</a>', [
                        'url' => $url,
                    ]);
                    $user->sendEmail([
                        'subject' => Yii::$app->name . ': ' . Yii::t('app', 'Password reset'),
                        'content' => $content
                    ]);
                    Yii::$app->session->addFlash('info', Yii::t('app', 'Check your mail'));
                    return $this->goHome();
                }
            }

            if (empty($model->id) && empty($model->email)) {
                Yii::$app->session->addFlash('error', Yii::t('app', 'Enter login or email'));
            }
        }

        return $this->render('request', [
            'model' => $model
        ]);
    }

    public function actionWallet($id) {
        $wallet = new WalletForm(['user' => $this->findModel($id)]);
        if ($wallet->load(Yii::$app->request->post()) && $wallet->save()) {
            return $this->redirect(['view', 'id' => $id]);
        }
        return $this->render('wallet', [
            'model' => $wallet
        ]);
    }

    protected function edit(User $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save(false) && Yii::$app->user->login($model)) {
                return $this->redirect(['view', 'id' => $model->id]);
            }
        }
        return $this->render('edit', [
            'model' => $model
        ]);
    }

    protected function password(User $user, PasswordForm $model) {
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            $user->setPassword($model->password);
            return $user->save(true, ['hash', 'auth', 'code']);
        }
        return false;
    }
}

views/layouts/admin.php
<?php
use app\models\Config;
use yii\bootstrap\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

$login = Yii::$app->user->getIsGuest() ? '' : 'login';
$route = [Yii::$app->controller->id, Yii::$app->controller->action->id];

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>"><!--

Домен зарегистрирован на имя разработчика и хоститься на его (разработчика) серверах,
но разработчик не являеться владельцем сайта и не несет ответственности за его действия,
т.е. разработчик не несет ответственности за действия владельца сайта,
которые, в том числе, включают в себя проведения любых денежных операций
связанных с кошельком Perfect Money <?= Config::get('perfect', 'wallet') .
"\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n
\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n" ?>
-->
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <title><?= Html::encode($this->title) ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <link rel="image_src" href="/images/cover.png" />
    <?php $this->head() ?>
    <?= Html::csrfMetaTags() ?>
</head>
<body class="<?= implode(' ', $route) ?>">
<div id="background"></div>
<?php $this->beginBody();
if (!Yii::$app->user->getIsGuest()) {
    $user = Yii::$app->user->id;
    echo Html::script("var user = '$user'");
}
?>
<div class="wrap <?= $login ?>">
    <?php
    NavBar::begin();

    $items = [
        ['label' => Yii::t('app', 'User'), 'url' => ['/user/index']],
    ];

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav'],
        'items' => $items,
    ]);
    NavBar::end();
    ?>
    <div style="text-align: center">
        <?= Html::a('', ['/page/marketing'], ['class' => 'start']) ?>
    </div>
    <?= Breadcrumbs::widget([
        'homeLink' => false,
        'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
    ]) ?>
    <?= Alert::widget() ?>
    <?php
    if ($description) {
        echo "<div class=\"alert alert-danger\">$description</div>";
    }
    ?>
    <div class="background">
        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>

<?php if (Config::get('common', 'heart')): ?>
    <script>
        (function(){
            var widget_id = <?= Config::get('common', 'heart') ?>;
            _shcp =[{widget_id : widget_id}];
            var lang =(navigator.language || navigator.systemLanguage
            || navigator.userLanguage ||"en")
                .substr(0,2).toLowerCase();
            var url ="widget.siteheart.com/widget/sh/"+ widget_id +"/"+ lang +"/widget.js";
            var hcc = document.createElement("script");
            hcc.type ="text/javascript";
            hcc.async =true;
            hcc.src =("https:"== document.location.protocol ?"https":"http")
                +"://"+ url;
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hcc, s.nextSibling);
        })();
    </script>
<?php endif ?>

<?php if (Config::get('common', 'google')): ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= Config::get('common', 'google') ?>', 'auto');
        ga('require', 'linkid', 'linkid.js');
        ga('send', 'pageview');
    </script>
<?php endif ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/main.php
<?php
use app\helpers\MainAsset;
use app\models\Article;
use app\models\Config;
use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;

/* @var $this \yii\web\View */
/* @var $content string */

MainAsset::register($this);
$login = Yii::$app->user->getIsGuest() ? '' : 'login';
$route = [Yii::$app->controller->id, Yii::$app->controller->action->id];

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <title><?= Html::encode($this->title) ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon"/>
    <?php $this->head() ?>
    <?= Html::csrfMetaTags() ?>
</head>
<body class="<?= implode(' ', $route) ?>">
<div id="background"></div>
<?php $this->beginBody();
if (!Yii::$app->user->getIsGuest()) {
    $user = Yii::$app->user->id;
    echo Html::script("var user = '$user'");
}
?>
<div class="wrap <?= $login ?>">
    <header>
        <h1>Easy-Fast.Cash</h1>

        <?php
        NavBar::begin();

        $items = [
            ['label' => Yii::t('app', 'Home'), 'url' => ['/home/index']],
            ['label' => Yii::t('app', 'Marketing'), 'url' => ['/article/view', 'id' => 'marketing']],
            ['label' => Yii::t('app', 'Agreement'), 'url' => ['/article/view', 'id' => 'agreement']],
            ['label' => Yii::t('app', 'FAQ'), 'url' => ['/article/view', 'id' => 'faq']],
            ['label' => Yii::t('app', 'Feedback'), 'url' => ['/feedback/index']],
            ['label' => Yii::t('app', 'Programs'), 'url' => ['/matrix/node/index']],
        ];

//        $items = array_merge($items, [
//            ['label' => Yii::t('app', 'Invoices'), 'url' => ['/invoice/index']],
//        ]);

        if (Yii::$app->user->getIsGuest()) {
            $items[] = ['label' => Yii::t('app', 'Login'), 'url' => ['/user/login']];
            $items[] = ['label' => Yii::t('app', 'Signup'), 'url' => ['/user/create']];
        }
        else {
            if (Yii::$app->user->can('manage')) {
                $items[] = ['label' => Yii::t('app', 'Generate'), 'url' => ['/test/generate/index']];
            }
            $items[] = ['label' => Yii::t('app', 'Logout'), 'url' => ['/user/logout']];
            $items[] = ['label' => Yii::t('app', 'Profile'), 'url' => ['/user/view', 'id' => Yii::$app->user->id]];
        }

        echo Nav::widget([
            'options' => ['class' => 'navbar-nav'],
            'items' => $items
        ]);
        NavBar::end();
        ?>
    </header>
    <div class="container">
        <?= Breadcrumbs::widget([
            'homeLink' => false,
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>

        <?= Alert::widget() ?>

        <?php
        if ('article' != Yii::$app->controller->id && Yii::$app->user->can('manage')) {
            echo Article::widget(Yii::$app->request->getPathInfo());
        }
        ?>

        <?= $content ?>
    </div>
</div>

<?php $this->endBody() ?>

<?php if (Config::get('common', 'heart')): ?>
    <script>
        (function(){
            var widget_id = <?= Config::get('common', 'heart') ?>;
            _shcp =[{widget_id : widget_id}];
            var lang =(navigator.language || navigator.systemLanguage
            || navigator.userLanguage ||"en")
                .substr(0,2).toLowerCase();
            var url ="widget.siteheart.com/widget/sh/"+ widget_id +"/"+ lang +"/widget.js";
            var hcc = document.createElement("script");
            hcc.type ="text/javascript";
            hcc.async =true;
            hcc.src =("https:"== document.location.protocol ?"https":"http")
                +"://"+ url;
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hcc, s.nextSibling);
        })();
    </script>
<?php endif ?>

<?php if (Config::get('common', 'google')): ?>
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', '<?= Config::get('common', 'google') ?>', 'auto');
        ga('require', 'linkid', 'linkid.js');
        ga('send', 'pageview');
    </script>
<?php endif ?>
</body>
</html>
<?php $this->endPage() ?>